version: "3"

services:
  angular_app:
    build:
      context: ./front-url
      dockerfile: Dockerfile
    ports:
      - 4200:4200
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data